---
apiVersion: v1
kind: Service
metadata:
  name: peopleapi-svc
  namespace: monitoring
labels:
  operated-prometheus: true  
spec:
  selector:
    app: peopleapi
    deploymentconfig: peopleapi
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      name: 7000-tcp
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: web
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: peopleapi
  namespace: monitoring
spec:
  selector:
    app: peopleapi
  replicas: 1
  template:
    metadata:
      labels:
        app: peopleapi
    spec:
      containers:
        - name: peopleapi
          image: peddadas/testhpa-repo:peopleapi
          ports:
            - containerPort: 7000
            - containerPort: 5000
